import '../utils/styles/reset.css'
import '../utils/styles/globals.css'
import { Metadata } from 'next'

import { Orbitron } from 'next/font/google'

const orbitron = Orbitron({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: {
        template: '%s | Kommo',
        default: 'Task 2 | Kommo',
    },
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
    <html className={orbitron.className} lang="en" suppressHydrationWarning={true}>
        <body className='flex flex-col justify-between' style={{ minHeight: '100vh' }}>
            {children}
        </body>
    </html>
)
export default RootLayout


// const RootLayout = ({ children }: { children: React.ReactNode }) => (
//     <html lang="en" suppressHydrationWarning={true}>
//         <body className='flex flex-col justify-between' style={{ minHeight: '100vh' }}>
//             <Providers>
//                 <General>
//                     {children}
//                 </General>
//             </Providers>
//         </body>
//     </html>
// )
// export default RootLayout